image: mcr.microsoft.com/dotnet/core/sdk:3.1

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'develop'     # Execute jobs when a new commit is pushed to develop branch
    - if: $CI_COMMIT_BRANCH == 'master'      # Execute jobs when a new commit is pushed to master branch

before_script:
    - 'cd Survello'
    - 'dotnet restore'

build_api:
    stage: build
    script:
        - 'dotnet build'
